// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: messagebus/v1/messagebus.proto

package messagebusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageBusService_Publish_FullMethodName   = "/messagebus.v1.MessageBusService/Publish"
	MessageBusService_Subscribe_FullMethodName = "/messagebus.v1.MessageBusService/Subscribe"
)

// MessageBusServiceClient is the client API for MessageBusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageBusServiceClient interface {
	// Publish a message to the specified topic
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Subscribe to a topic (streaming)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MessageBusService_SubscribeClient, error)
}

type messageBusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBusServiceClient(cc grpc.ClientConnInterface) MessageBusServiceClient {
	return &messageBusServiceClient{cc}
}

func (c *messageBusServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, MessageBusService_Publish_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBusServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MessageBusService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageBusService_ServiceDesc.Streams[0], MessageBusService_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &messageBusServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MessageBusService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type messageBusServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *messageBusServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageBusServiceServer is the server API for MessageBusService service.
// All implementations should embed UnimplementedMessageBusServiceServer
// for forward compatibility
type MessageBusServiceServer interface {
	// Publish a message to the specified topic
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Subscribe to a topic (streaming)
	Subscribe(*SubscribeRequest, MessageBusService_SubscribeServer) error
}

// UnimplementedMessageBusServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMessageBusServiceServer struct {
}

func (UnimplementedMessageBusServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedMessageBusServiceServer) Subscribe(*SubscribeRequest, MessageBusService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

// UnsafeMessageBusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBusServiceServer will
// result in compilation errors.
type UnsafeMessageBusServiceServer interface {
	mustEmbedUnimplementedMessageBusServiceServer()
}

func RegisterMessageBusServiceServer(s grpc.ServiceRegistrar, srv MessageBusServiceServer) {
	s.RegisterService(&MessageBusService_ServiceDesc, srv)
}

func _MessageBusService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBusServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBusService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBusServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBusService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageBusServiceServer).Subscribe(m, &messageBusServiceSubscribeServer{stream})
}

type MessageBusService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type messageBusServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *messageBusServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

// MessageBusService_ServiceDesc is the grpc.ServiceDesc for MessageBusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messagebus.v1.MessageBusService",
	HandlerType: (*MessageBusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _MessageBusService_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MessageBusService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messagebus/v1/messagebus.proto",
}
